# Seedkeeper Development Stack - Hot-reload enabled
# This compose file mounts the app directory for development
# Changes to Python files will be picked up immediately via hot-reload
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: seedkeeper-dev-redis
    restart: unless-stopped
    volumes:
      - redis-dev-data:/data
      - /storage/docker/seedkeeper/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme123}
    healthcheck:
      test: redis-cli -a "$$REDIS_PASSWORD" ping
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gateway:
    image: seedkeeper:latest
    container_name: seedkeeper-dev-gateway
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # Mount app directory for hot-reload development
      - /storage/docker/seedkeeper/app:/app
      - /storage/docker/seedkeeper/data:/app/data
      - /storage/docker/seedkeeper/views:/app/views:ro
    env_file:
      - /storage/docker/seedkeeper/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme123}
      - PYTHONUNBUFFERED=1
    working_dir: /app
    entrypoint: ["python"]
    command: ["seedkeeper_gateway.py"]
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.5
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "homepage.group=AI Services"
      - "homepage.name=Seedkeeper Dev Gateway"
      - "homepage.icon=discord.png"
      - "homepage.description=Development gateway with hot-reload"
      - "com.centurylinklabs.watchtower.enable=false"

  worker:
    image: seedkeeper:latest
    container_name: seedkeeper-dev-worker
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
      # Mount app directory for hot-reload development
      - /storage/docker/seedkeeper/app:/app
      - /storage/docker/seedkeeper/data:/app/data
      - /storage/docker/seedkeeper/views:/app/views:ro
    env_file:
      - /storage/docker/seedkeeper/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme123}
      - PYTHONUNBUFFERED=1
    working_dir: /app
    entrypoint: ["python"]
    command: ["seedkeeper_worker.py"]
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    labels:
      - "homepage.group=AI Services"
      - "homepage.name=Seedkeeper Dev Worker"
      - "homepage.icon=bot.png" 
      - "homepage.description=Development worker with hot-reload"
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  redis-dev-data:

networks:
  default:
    external: true
    name: seg_iot